[package]
name = "Wallet-Ledger"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0.149"

[[bin]]
name = "wallet-ledger"
path = "src/main.rs"
